version: '3.7'

services:
  mongodb:
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-example}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_DB:-root}
    ports:
      - '28017:27017'
    volumes:
      - ./mongodb-data:/data/db
      - ./mongodb-log:/var/log/mongodb
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

  meter-config-service:
    depends_on:
      - mongodb
    profiles:
      - registry
    image: ghcr.io/lumina360/meter-config-service:latest
    ports:
      - '8080:8080'

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local