## This workflow uses actions that are not certified by GitHub.
## They are provided by a third-party and are governed by
## separate terms of service, privacy policy, and support
## documentation.
## This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
#
#name: Java CI with Gradle
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build_and_publish:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 22
#      uses: actions/setup-java@v4
#      with:
#        java-version: '22'
#        distribution: 'temurin'
#        cache: 'gradle'
#
#    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
#    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
#    - name: Setup Gradle
#      uses: gradle/actions/setup-gradle@v3.3.2
#      with:
#        gradle-version: '8.8'
#
#
#
#
#    - name: Build and Publish with Gradle
#      uses: gradle/gradle-build-action@v2
#      with:
#        arguments: jib
#
#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_REGION }}
#
#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v1
#
#    - name: Push image
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        ECR_REPOSITORY: my-springboot-app # Replace with your ECR repository name
#        IMAGE_TAG: latest
#      run: |
#        docker tag ${{ github.repository }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG